defaults: &defaults
  docker:
    - image: circleci/node:latest
  working_directory: ~/cicd-example
version: 2.1
jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths: .
  tests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/cicd-example
      - run: npm install
      - run: npm test
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/cicd-example
      - run:
        name: Install Now CLI
        command: sudo npm install --global --unsafe-perm now
      - deploy:
        name: Deploy & Alias
        command: |
          now --token $ZEIT_TOKEN --local-config now.json
          now --token $ZEIT_TOKEN --local-config now.json alias

workflows:
  version: 2.1
  deploy_with_tests:
    jobs:
      - checkout
      - tests:
          requires:
            - checkout
      - deploy:
          requires:
            - tests
