version: 2.1
jobs:
  build:
    working_directory: ~/cicd-example
    docker:
      - image: circleci/node:latest
      - image: mongo:3.4.4
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
